linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - hugeParam

linters:
  enable:
    - revive
    - errcheck
    - ineffassign
    - gosec
    - unconvert
    - dupl
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - nakedret
    - gocritic
    - gochecknoinits
    - gochecknoglobals
    - prealloc
    - lll
    - gosimple
    - errcheck
    - staticcheck
    - govet
    - unused
  fast: true
  disable:
    - typecheck

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - gosec

    # Exclude lll issues for long lines with go:generate
    - linters:
        - lll
      source: "^//go:generate "

# golangci.com configuration
# https://github.com/golangci/golangci/wiki/Configuration
service:
  golangci-lint-version: 1.19.x # use the fixed version to not introduce new linters unexpectedly