#!/usr/bin/env bash

staged_files=$(git diff --diff-filter=d --cached --name-only | grep -E '\.(go)$')

echo "run golangci-lint..."

fail=0
msg=""

for file in $staged_files
do
  echo "checking $file"
  golangci-lint run --fix "$file" --disable typecheck
  if [ $? -ne 0 ]; then
    (( fail++ ))
  fi
done

if [ $fail -gt 0 ]
then
  echo "$fail linter errors found, please fix it before commiting again."
  exit 1  
fi

echo "no linter error found, commiting..."